import Head from "next/head";
import Image from "next/image";
import FeedBackDetails from "../components/feedbacks";
import Suggestions from "../components/suggestions";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className="px-[10.3rem] py-[5.8rem]">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <FeedBackDetails />
    </div>
  );
}
